<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="mb-2 block text-sm font-medium">Nama Lengkap</label><input name="name" value="{{ old('name', $customer->name ?? '') }}" required class="w-full rounded-lg border border-zinc-300 px-3 py-2">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="mb-2 block text-sm font-medium">NIK</label><input name="nik" value="{{ old('nik', $customer->nik ?? '') }}" inputmode="numeric" maxlength="16" class="w-full rounded-lg border border-zinc-300 px-3 py-2">@error('nik')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="mb-2 block text-sm font-medium">Tempat Lahir</label><input name="birth_place" value="{{ old('birth_place', $customer->birth_place ?? '') }}" class="w-full rounded-lg border border-zinc-300 px-3 py-2"></div>
    <div><label class="mb-2 block text-sm font-medium">Tanggal Lahir</label><input type="date" name="birth_date" value="{{ old('birth_date', $customer?->birth_date?->format('Y-m-d')) }}" class="w-full rounded-lg border border-zinc-300 px-3 py-2"></div>
    <div><label class="mb-2 block text-sm font-medium">Status Perkawinan</label><select name="marital_status" class="w-full rounded-lg border border-zinc-300 px-3 py-2"><option value="">Pilih Status</option>@foreach(['Belum Menikah','Menikah'] as $status)<option value="{{ $status }}" @selected(old('marital_status', $customer->marital_status ?? '') === $status)>{{ $status }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm font-medium">Pekerjaan</label><input name="occupation" value="{{ old('occupation', $customer->occupation ?? '') }}" class="w-full rounded-lg border border-zinc-300 px-3 py-2"></div>
    <div><label class="mb-2 block text-sm font-medium">Telepon</label><input name="phone" value="{{ old('phone', $customer->phone ?? '') }}" class="w-full rounded-lg border border-zinc-300 px-3 py-2"></div>
    <div><label class="mb-2 block text-sm font-medium">Email</label><input type="email" name="email" value="{{ old('email', $customer->email ?? '') }}" class="w-full rounded-lg border border-zinc-300 px-3 py-2">@error('email')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
</div>
<div><label class="mb-2 block text-sm font-medium">Alamat</label><textarea name="address" rows="4" class="w-full rounded-lg border border-zinc-300 px-3 py-2">{{ old('address', $customer->address ?? '') }}</textarea></div>
